{{- if .Values.persistence.enabled }}
# Data PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-data
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
---
{{- if .Values.redis.useConfigFile }}
# Config PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc-config
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.configSize }}
{{- end }}
{{- end }}
