FROM ubuntu:22.04
LABEL maintainer="striveonger@163.com"
LABEL version="1.0.0"

ENV JAVA_HOME=/opt/java
ENV PATH=$JAVA_HOME/bin:$PATH

COPY Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone



