annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add Prometheus metrics via native plugin and ServiceMonitor
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: EE19FA216B8349AC017C5279B4C062080CDC2061C264EE92CF98300E39FD40A8
    url: https://kubelauncher.github.io/charts/cosign.pub
apiVersion: v2
appVersion: 4.2.5
description: RabbitMQ message broker
home: https://github.com/kubelauncher/charts
icon: https://cdn.simpleicons.org/rabbitmq
keywords:
- rabbitmq
- message queue
- AMQP
- broker
maintainers:
- email: platform@kubelauncher.com
  name: kubelauncher
  url: https://www.kubelauncher.com
name: rabbitmq
sources:
- https://github.com/kubelauncher/docker
- https://github.com/kubelauncher/charts
type: application
version: 0.1.17
