global:
  redis:
    password: "A123456a"
image:
  registry: "docker.io"
  repository: "bitnami/redis"
  tag: "8.6.2"
  pullPolicy: "IfNotPresent"

## @param architecture Redis(R) architecture. Allowed values: `standalone` or `replication`
##
architecture: "standalone"
