# PostgreSQL specific values
postgresql:
  postgresPassword: "A123456a"

# Resource configuration
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# Service configuration
service:
  type: ClusterIP
  port: 5432
