apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rocketmq.fullname" . }}-broker
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
    component: broker
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rocketmq.selectorLabels" . | nindent 6 }}
      component: broker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rocketmq.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        component: broker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rocketmq.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: broker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - "rm -f /home/rocketmq/rocketmq-5.3.1/logs/rocketmqlogs/*.log && nohup /home/rocketmq/rocketmq-5.3.1/bin/mqbroker -n {{ include "rocketmq.fullname" . }}-ns:9876 > /home/rocketmq/rocketmq-5.3.1/logs/rocketmqlogs/broker.log 2>&1"
          ports:
            - name: broker
              containerPort: {{ .Values.broker.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "netstat -an | grep :{{ .Values.broker.port }} >/dev/null 2>&1"
            initialDelaySeconds: 60
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "netstat -an | grep :{{ .Values.broker.port }} >/dev/null 2>&1"
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.broker.resources | nindent 12 }}
          volumeMounts:
            - name: rocketmq-data
              mountPath: /home/rocketmq/rocketmq-5.3.1/logs
            - name: rocketmq-data
              mountPath: /home/rocketmq/rocketmq-5.3.1/store
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: rocketmq-data
          persistentVolumeClaim:
            claimName: {{ include "rocketmq.fullname" . }}-data-pvc
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
