apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-ns
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
    component: nameserver
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nameserver
      port: {{ .Values.nameserver.port }}
      targetPort: nameserver
      protocol: TCP
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    component: nameserver
