apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketmq.fullname" . }}-broker
  labels:
    {{- include "rocketmq.labels" . | nindent 4 }}
    component: broker
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: broker
      port: {{ .Values.broker.port }}
      targetPort: broker
      protocol: TCP
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    component: broker
